import bcrypt from "bcryptjs"
import config from "../../config"
import { prisma } from "../../lib/prisma"
import { Role } from "../../../generated/prisma/enums"
import { ICategoryPayload, IUpdateCategoryPayload } from "./category.interface"
